Repository Data-Sculptor-X/VOJ-ReactJS, pull requests merged in 2024-10, with the labels that each got.

#10 #Add greetings.yml
  .github/workflows/greetings.yml
Labels: hacktober-accepted, -gssoc-ext, level1

#21 Feat: Add Issue, PR Templates
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/Pull_Request_Template.md
Labels: documentation, hacktober-accepted, gssoc-ext, hacktoberfest

#22 Signup form responsiveness
  src/components/Login/style.css
Labels: enhancement, good first issue, hacktober-accepted, gssoc-ext, level3, hacktoberfest

#26 Add some Responsive features
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/Pull_Request_Template.md
  .github/workflows/greetings.yml
  Code_Of_Conduct.md
  DesktopApp/main.js
  README.md
  et --hard 4f449dbf0e7905f447fe17e8acd6d8faf36781ba
  package.json
  public/index.html
  public/manifest.json
  src/assets/css/argon-dashboard-pro-react.css
  src/assets/css/argon-dashboard-pro-react.min.css
  src/assets/don.jpeg
  src/assets/google-svgrepo-com.svg
  src/assets/img/logo.ico
  src/assets/logo.png
  src/assets/placeholder.png
  src/assets/robot.png
  src/assets/user.svg
  src/components/Chatpage/chat.js
  src/components/Footers/AdminFooter.js
  src/components/ForgotPassword/ForgotPassword.js
  src/components/ForgotPassword/ForgotPasswordComponent.css
  src/components/ForgotPassword/ResetPassword.css
  src/components/ForgotPassword/ResetPassword.js
  src/components/Home Page/HomePage.js
  src/components/Homepage/home.css
  src/components/Homepage/home.js
  src/components/Indian Laws/IndianLaws.js
  src/components/Law News/LawNews.js
  src/components/Lawyers List/LawyersList.css
  src/components/Lawyers List/Lawyerslist.js
  src/components/Login/Login.jsx
  src/components/Login/LoginApp.jsx
  src/components/Login/SignUpForm.jsx
  src/components/Login/style.css
  src/components/Navbars/AdminNavbar.js
  src/components/Privacy Policy/PrivacyPolicy.js
  src/components/Sidebar/Sidebar.js
  src/components/Verify Email/VerifyEmail.js
  src/config.js
  src/index.js
  src/layouts/MasterAdmin.js
  src/react-speech-kit.d.ts
  src/routers.js
  src/store/actions/General/authActions.js
  src/store/reducer/General/authReducer.js
  src/store/reducer/General/newauthReducer.js
  src/store/reducer/rootReducer.js
  src/store/store.js
  src/variables/en.json
  src/variables/hi.json
  src/variables/ta.json
  src/views/pages/Widgets.js
  src/views/pages/components/Cards.js
  src/views/pages/dashboards/Dashboard.js
  src/views/pages/forms/Elements.js
Labels: hacktober-accepted, gssoc-ext, hacktoberfest

#25 Created Readme.md file
  README.md
  image.png
Labels: hacktober-accepted, level1, gssoc-ext, hacktoberfest

#48 Create auto-comment-on-close.yml
  .github/workflows/auto-comment-on-close.yml
Labels: enhancement, hacktober-accepted, gssoc-ext, level2, hacktoberfest

#41 ✨added multi language support system✨
  .vscode/settings.json
  public/index.html
Labels: enhancement, hacktober-accepted, level1, gssoc-ext, hacktoberfest
